// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Documentação existente (tutorial)
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'}, {type: 'autogenerated', dirName: 'tutorial-extras'}],

  // Nova documentação de JavaScript
  javascriptSidebar: [
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'javascript/intro',
        {
          type: 'category',
          label: 'Tipos de Dados',
          items: [
            'javascript/tipos-dados/symbol',
            'javascript/tipos-dados/bigint',
            'javascript/tipos-dados/typeof',
          ],
        },
        {
          type: 'category',
          label: 'Strings',
          items: [
            'javascript/strings/concatenacao',
          ],
        },
        {
          type: 'category',
          label: 'Console e Debugging',
          items: [
            'javascript/console/console-basico',
          ],
        },
        {
          type: 'category',
          label: 'Assincronia',
          items: [
            'javascript/assincronia/async-await',
            'javascript/assincronia/tratamento-erros',
            'javascript/assincronia/throw',
          ],
        },
        {
          type: 'category',
          label: 'Programação Orientada a Objetos',
          items: [
            'javascript/poo/classes',
            'javascript/poo/static',
            'javascript/poo/private-get-set',
          ],
        },
        {
          type: 'category',
          label: 'Operadores',
          items: [
            'javascript/operadores/spread-rest',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
